version: '3.8'

# ==============================================================================
# Stack : Core Infrastructure (Pi 5)
# Services : Portainer (Gestion Docker), Nginx Proxy Manager (Reverse Proxy), PostgreSQL (BDD)
# ==============================================================================

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # Les mots de passe sont protégés par des variables grâce à ton fichier .gitignore !
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  portainer_data:
  npm_data:
  npm_letsencrypt:
  postgres_data:
